name: CI/CD Demo Test Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest and generate HTML report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report-${{ matrix.os }}-py${{ matrix.python-version }}
          path: report.html

      - name: Notify Slack on success
        if: success() && github.event_name != 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ CI Tests passed on ${{ matrix.os }} with Python ${{ matrix.python-version }}."}' $SLACK_WEBHOOK_URL

      - name: Notify Slack on failure
        if: failure() && github.event_name != 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ CI Tests FAILED on ${{ matrix.os }} with Python ${{ matrix.python-version }}. Check details: ${{ github.run_url }}"}' $SLACK_WEBHOOK_URL

      - name: Send Email notification (on failure only)
        if: failure() && github.event_name != 'pull_request'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI Tests Failed - ${{ github.repository }}"
          to: youremail@example.com
          from: github-actions@example.com
          body: "CI tests failed for ${{ github.repository }} on ${{ matrix.os }} with Python ${{ matrix.python-version }}. See details: ${{ github.run_url }}"
          secure: true
